DROP TABLE if exists users, films, film_genres, rating, genres, likes, friends;

CREATE TABLE IF NOT EXISTS users
(
    user_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(30) NOT NULL,
    login    VARCHAR(30) NOT NULL,
    name     VARCHAR(30),
    birthday DATE
);

CREATE TABLE IF NOT EXISTS films
(
    film_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(30) NOT NULL,
    description  VARCHAR(200),
    release_date DATE,
    duration     INTEGER,
    rating_id    INTEGER
);

CREATE TABLE IF NOT EXISTS genres
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS rating
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(30) NOT NULL
);

ALTER TABLE films
    ADD FOREIGN KEY (rating_id) REFERENCES rating;

CREATE TABLE IF NOT EXISTS film_genres
(
    film_id INTEGER NOT NULL
        REFERENCES films ON DELETE CASCADE,
    id      INTEGER NOT NULL
        REFERENCES genres,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS likes
(
    film_id INTEGER NOT NULL
        REFERENCES films ON DELETE CASCADE,
    user_id INTEGER NOT NULL
        REFERENCES users,
    PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS friends
(
    user_id   INTEGER NOT NULL
        REFERENCES users ON DELETE CASCADE,
    friend_id INTEGER NOT NULL
        REFERENCES users,
    PRIMARY KEY (user_id, friend_id)
);

MERGE INTO rating (id, title)
    VALUES (1, 'G'),
           (2, 'PG'),
           (3, 'PG-13'),
           (4, 'R'),
           (5, 'NC-17');

MERGE INTO genres (id, name)
    VALUES (1, 'Комедия'),
           (2, 'Драма'),
           (3, 'Мультфильм'),
           (4, 'Триллер'),
           (5, 'Документальный'),
           (6, 'Боевик');

INSERT INTO films (name, description, release_date, duration, rating_id)
VALUES ('film1', 'description1', '1981-01-01', 101, 1),
       ('film2', 'description2', '1982-02-02', 102, 2),
       ('film3', 'description3', '1983-03-03', 103, 3),
       ('film4', 'description4', '1984-04-04', 104, 4);

INSERT INTO users (email, login, name, birthday)
VALUES ('email1', 'login1', 'name1', '1981-01-01'),
       ('email2', 'login2', 'name2', '1982-02-02'),
       ('email3', 'login3', 'name3', '1983-03-03');
